name: Schedule Kaggle Notebook Run

on:
  schedule:
    # Schedule the notebook to run at 8 AM every day
    - cron: '0 8 * * *'

jobs:
  run-kaggle-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Kaggle CLI
      run: pip install kaggle

    - name: Set up Kaggle API credentials
      run: |
        mkdir -p ~/.kaggle
        echo "$KAGGLE_KEY" > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json
      env:
        KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

    - name: Run Kaggle Notebook
      run: |
        kaggle kernels pull ayansarkar/rsna-data-description -p /tmp
        cd /tmp/<kernel>
        kaggle kernels push
